title: 村民式毒物流TRPG 0.0.1
description: 核心規則書與判定指南
theme: just-the-docs

url: https://lazyjim84923.github.io
baseurl: /uh

search_enabled: true
search_placeholder_text: 搜尋規則書內容...

# 核心搜尋設定：強制開啟中文分詞支援
search:
  tokenizer_separator: /[\s\-\p{P}]+|(?=[\u4e00-\u9fa5])/u
  preview_words_before: 10
  preview_words_after: 10
